FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.3-alpine AS base
WORKDIR /app
# EXPOSE 5000

FROM mcr.microsoft.com/dotnet/core/sdk:3.1.201-alpine AS build
WORKDIR /app
COPY . .
RUN dotnet restore
RUN dotnet build -c Release -o /out/build

FROM build AS publish
RUN dotnet publish -c Release -o /out/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /out/publish .
ENTRYPOINT [ "dotnet", "IncomeTaxCalculator.dll" ]
